package:
  name: hello
  version: 2.12
  epoch: 0
  description: "an example of how conditionals influence build behavior"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      license: Not-Applicable
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
    packages:
      - alpine-baselayout-data
      - busybox
      - ca-certificates-bundle

pipeline:
  - working-directory: /home/build/foo
    runs: |
      echo "current working directory: $(pwd)"
  - working-directory: /home/build/bar
    pipeline:
      - runs: |
          echo "current working directory: $(pwd)"
      - working-directory: /home/build/baz
        runs: |
          echo "current working directory: $(pwd)"
  - runs: |
      mkdir -p "${{targets.destdir}}"
